### ISSUE TITLE
Update PyPi with tarball including license file

### ISSUE THREAD

**Issue by hogarthj** [kurtraschke/pyRFC3339#5]
Hi,

I'm in the process of packaging this for Fedora as it's been identified as a dependency for the LetsEncrypt client.

The Fedora packaging guidelines have a strong preference to the license being in a separate file from upstream that can then be included.

This file appears to already be in the github repo but is missing from the tarball over on Pypi.

Could you please upload a new archive to PyPi including this?

**Comment by hogarthj** [comment]
Also the license file in this repo doesn't appear to match the license in the PyPi upload which states it is MIT, and the file here does not reflect that.

**Comment by kurtraschke** [comment]
This was fixed in 9d57ef with the addition of a `MANIFEST.in` file, and was included in the 1.0 release which has been uploaded to PyPI.

As to the text of the license, can you please clarify?  The contents of [LICENSE.txt](https://github.com/kurtraschke/pyRFC3339/blob/6ffad1620d6ece8bb8c4b93308aed8a312c96148/LICENSE.txt) are identical to the OSI-approved [MIT license](https://opensource.org/licenses/MIT).

**Comment by hogarthj** [comment]
That upload is perfect thanks for responding so quickly!

I'll update my package review request this evening. Appreciate the quick turn around.
